/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class count_agent_NewEvent */

#ifndef _Included_count_agent_NewEvent
#define _Included_count_agent_NewEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     count_agent_NewEvent
 * Method:    nativeNewEvent
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_count_agent_NewEvent_nativeNewEvent
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
